version: '3'
services:
  backend:
    build: ./pokemon-battle-backend # โฟลเดอร์ backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  frontend:
    build: ./pokemon_battle_front # โฟลเดอร์ frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vkiydKN8825 # รหัสผ่านของคุณ
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: